env:
  - GO11MODULE=0
  - CGO_ENABLED=0
before:
  hooks:
    - go mod download
builds:
  - binary: golangci-lint
    goos:
      - darwin
      - windows
      - linux
      - freebsd
    goarch:
      - amd64
      - arm64
      - arm
      - 386
      - ppc64le
      - s390x
    goarm:
      - 6
      - 7
    ldflags: -s -w
archives:
  - format: tar.gz
    wrap_in_directory: false
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md
