language: go
env:
  # BUG(komish): Workaround, see https://github.com/komish/unstaged/issues/14
  - GO111MODULE=on UNSTAGED_COMMIT_HASH="-" UNSTAGED_VERSION="dev"
go:
  - 1.12.x
  - 1.13.x

install: true
script: 
  - go build
  - go test -v ./...


# calls goreleaser
# deploy:
#   - provider: script
#     skip_cleanup: true
#     script: curl -sL https://git.io/goreleaser | bash
#     on:
#       tags: true
#       # it's important to build only on one item in matrix
#       condition: $TRAVIS_GO_VERSION =~ ^1\.13
